- hosts: all
  user: {{ sudouser }}
  sudo: True
  
  tasks:
    - name: stop mysql daemon
      shell: stop mysql
    - name: copy no grant table mysql start script to remote
      action: copy src=../files/start-mysql-with-reinit-file dest=/tmp/start-mysql-with-reinit-file mode=700 owner=root group=root
    - name: create dir in /var/lib/mysql for init file
      action: shell [ -d /var/lib/mysql/initfiles ] || install -d /var/lib/mysql/initfiles
    - name: copy reinit mysql script
      action: copy src=../files/reinit-mysql dest=/var/lib/mysql/initfiles/reinit-mysql mode=644 owner=root group=root
    - name: start mysql with reinit file
      action: shell /tmp/start-mysql-with-reinit-file
    - name: kill reinit mysqld
      action: shell killall mysqld
    - name: start mysql as typical would
      action: shell start mysql
    - name: cleanup temp files
      action: shell rm -rf /tmp/start-mysql-with-reinit-file /var/lib/mysql/initfiles
